### PR TITLE
Support use of DCMQI as a C++ library, building as a standalone package and/or Slicer extension

### PR DESCRIPTION
**Pull request by jcfr**
This topic incrementally fixes issue with the build system, then it adds the following functionality:
* Support building against DCMQI to use it as a library. It currently only support building against a build tree of DCMQI.
* Support building of DCMQI apps outside of DCMQI and against DCMQI as a library
* Support building of DCMQI as Slicer Remote extensions. See [here](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_system/Remote_Module) and [here](https://github.com/Slicer/Slicer/blob/869bb1e4370e5063a5c6fc15543a0abce3ee9459/CMakeLists.txt#L1007-L1016).
* Support building of DCMQI as a Slicer extension.

All of these scenario were manually tested on Ubuntu 15.04  (gcc 5.2.1 20151010) against Slicer [r25520](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25520). Note that it also expected to work against Slicer 4.6.2 [r25516](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25516)

Next steps:
* Manually confirm extension can be built against MacOSX and Windows build tree

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov @che85 

After this topic is integrated into `master` and the corresponding extension added to the [ExtensionsIndex](https://github.com/Slicer/ExtensionsIndex/), the DCMQI C++ library could be used in the Reporting extension by:
1. adding DCMQI as one of its dependency 
2. calling `find_package(DCMQI REQUIRED)`
3. including headers with `#include <dcmqi/NameOfHeader.h>`
4. adding `dcmqi` in the appropriate `target_link_libraries` call

Notes:
* if there are resources (data files, json, xml, ...) that need to be made available to user of the C++ library, make sure let me know so that I can update the build system to expose them.
* if you anticipate adding more that one library to DCMQI, now would be a good time to finalize the naming scheme

Et voila

**Comment by jcfr** [comment]
Todo:
* [ ] Add logo. See #120

**Comment by jcfr** [comment]
And here is the results of compiling against the 4.6.2 build tree on the factory:

### MacOSX

There is one build error:

```
/Users/kitware/Dashboards/Experimental/dcmqi/libsrc/ImageSEGConverter.cpp:339:56: error: no viable conversion from 'OFVector<DcmDataset *>'
      to 'const OFVector<OFString>'
           CHECK_COND(derimgItem->addSourceImageItems(siVector,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Users/kitware/Dashboards/Experimental/dcmqi/include/dcmqi/Exceptions.h:11:9: note: expanded from macro 'CHECK_COND'
    if (condition.bad()) { \
        ^
/Users/kitware/Dashboards/Package/Slicer-462-package/DCMTK/ofstd/include/dcmtk/ofstd/ofvector.h:94:5: note: candidate constructor not viable:
      no known conversion from 'OFVector<DcmDataset *>' to 'const OFVector<OFString> &' for 1st argument;
    OFVector(const OFVector& other) : values_(NULL), allocated_(0), size_(0)
    ^
/Users/kitware/Dashboards/Package/Slicer-462-package/DCMTK/dcmfg/include/dcmtk/dcmfg/fgderimg.h:202:69: note: passing argument to parameter
      'files' here
  virtual OFCondition addSourceImageItems(const OFVector<OFString>& files,
                                                                    ^
/Users/kitware/Dashboards/Experimental/dcmqi/libsrc/ImageSEGConverter.cpp:339:56: error: no viable conversion from 'OFVector<DcmDataset *>'
      to 'const OFVector<OFString>'
            CHECK_COND(derimgItem->addSourceImageItems(siVector,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Users/kitware/Dashboards/Experimental/dcmqi/include/dcmqi/Exceptions.h:12:44: note: expanded from macro 'CHECK_COND'
      std::cerr << "Condition failed: " << condition.text() << " in " __FILE__ << ":" << __LINE__ << std::endl; \
                                           ^
/Users/kitware/Dashboards/Package/Slicer-462-package/DCMTK/ofstd/include/dcmtk/ofstd/ofvector.h:94:5: note: candidate constructor not viable:
      no known conversion from 'OFVector<DcmDataset *>' to 'const OFVector<OFString> &' for 1st argument;
    OFVector(const OFVector& other) : values_(NULL), allocated_(0), size_(0)
    ^
/Users/kitware/Dashboards/Package/Slicer-462-package/DCMTK/dcmfg/include/dcmtk/dcmfg/fgderimg.h:202:69: note: passing argument to parameter
      'files' here
  virtual OFCondition addSourceImageItems(const OFVector<OFString>& files,
                                                                    ^
2 errors generated.
make[5]: *** [libsrc/CMakeFiles/dcmqi.dir/ImageSEGConverter.cpp.o] Error 1
make[4]: *** [libsrc/CMakeFiles/dcmqi.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dcmqi-prefix/src/DCMQI-stamp/DCMQI-build] Error 2
make[1]: *** [CMakeFiles/DCMQI.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jcfr** [comment]
Here is the summary of building against Slicer trunk build tree (r25520)

## MacOSX (factory.kitware):  OK

```bash
git clone git://github.com/jcfr/dcmqi
mkdir dcmqi-slicer-Release && cd $_

Slicer_DIR=/Users/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/
~/Dashboards/Support/CMake-3.5.0-rc3.app/Contents/bin/cmake \
  -DSlicer_DIR:PATH=$Slicer_DIR \
  -DCMAKE_C_COMPILER=/Developer/usr/bin/clang \
  -DCMAKE_CXX_COMPILER=/Developer/usr/bin/clang++ \
  $(for opt in $(cat $Slicer_DIR/CMakeCache.txt | grep CMAKE_OSX | tr "\n" " "); do echo -n "-D$opt "; done) \
  -DCMAKE_BUILD_TYPE:STRING=Release \
   ../dcmqi
make
cd dcmqi-build
make package
```

and the content of the package:

```
factory@kitware:/Users/kitware/Dashboards/Experimental/dcmqi-slicer-Release/dcmqi-slicer-Release/dcmqi-build/_CPack_Packages/Darwin/TGZ/25520-macosx-amd64-DCMQI-git09d03e2-2016-11-11> find .
.
./Slicer.app
./Slicer.app/Contents
./Slicer.app/Contents/Extensions-25520
./Slicer.app/Contents/Extensions-25520/DCMQI
./Slicer.app/Contents/Extensions-25520/DCMQI/lib
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/itkimage2segimage
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/itkimage2segimage.xml
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/libitkimage2segimageLib.a
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/libsegimage2itkimageLib.a
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/libtid1500readerLib.a
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/libtid1500writerLib.a
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/segimage2itkimage
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/segimage2itkimage.xml
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/tid1500reader
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/tid1500reader.xml
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/tid1500writer
./Slicer.app/Contents/Extensions-25520/DCMQI/lib/Slicer-4.7/cli-modules/tid1500writer.xml
./Slicer.app/Contents/Extensions-25520/DCMQI/share
./Slicer.app/Contents/Extensions-25520/DCMQI/share/Slicer-4.7
./Slicer.app/Contents/Extensions-25520/DCMQI/share/Slicer-4.7/DCMQI.s4ext
```

## Linux (factory-south-ubuntu): Failing because Slicer trunk has ITK build errors

```bash
git clone git://github.com/jcfr/dcmqi
mkdir dcmqi-slicer-Release && cd $_

Slicer_DIR=/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/
/home/kitware/Dashboards/Support/cmake-3.5.0-rc3-Linux-x86_64/bin/cmake \
  -DSlicer_DIR:PATH=$Slicer_DIR \
  -DCMAKE_BUILD_TYPE:STRING=Release \
   ../dcmqi
make
cd dcmqi-build
make package
```

## Windows (factory-south-win7):  Originally failing because Slicer trunk failed to build (SimpleITK failing to download lua), I re-configured the top-level build tree disabling simpleITK and restarted the build. 

Status: build in progress

```bash
git clone git://github.com/jcfr/dcmqi
mkdir dcmqi-slicer-Release && cd $_

Slicer_DIR=/c/D/N/Slicer-1-build/Slicer-build/
/c/D/Support/cmake-3.5.0-rc3/bin/cmake.exe \
  -DSlicer_DIR:PATH=$Slicer_DIR \
   ../dcmqi
/c/D/Support/cmake-3.5.0-rc3/bin/cmake.exe --build . --config Release
cd dcmqi-build
/c/D/Support/cmake-3.5.0-rc3/bin/cmake.exe --build . --config Release --target package
```

**Comment by fedorov** [comment]
Great work @jcfr! I am very happy to see this progress!

I say - let's get it into nightly, make sure things work in the packaged Slicer, start integration with Reporting, and not worry about making dcmqi work with the stable for now. @pieper let us know what you think.

**Pull request merged**
