### PR TITLE
ENH: add logo

### PR DESCRIPTION
**Pull request by fedorov**
Let's use this one for now for Slicer extension, and improve later?

re #116

### CODE REVIEW

**Comment by jcfr** [comment]
Great. I will integrate it.

**Comment by jcfr** [comment]
Note: When adding commit that do not need to run the CI, you could add `[ci skip]` in the commit message. That way, it would leave the queue available for other topic.

**Comment by fedorov** [comment]
> you could add `[ci skip]` in the commit message

Nice, I had no idea - thanks!

**Comment by jcfr** [comment]
Thanks

I am closing. This is superseded by #121

**Pull request closed without merging**
