### PR TITLE
In memory objects only for segmentation converters

### PR DESCRIPTION
**Pull request by che85**
will fail in build system since some methods are only available with commit https://github.com/michaelonken/dcmtk/commit/82e831f112fd69eb461da6e282e0754ad48458cf

ctest succeeded

### CODE REVIEW

**Comment by fedorov** [comment]
appveyor failed!

**Comment by che85** [comment]
@fedorov As I said, we need to update the dcmtk revision because addSourceImageItems with the currently used one does not support OFVector<DcmDataset*> but takes OFVector<OFString> which are filenames....

**Comment by fedorov** [comment]
sorry, I missed that. 

This is frustrating, because this means we cannot integrate this into Slicer until the changes in @michaelonken private branch propagate into dcmtk master ...

not quite sure how to deal with this

**Comment by che85** [comment]
As a workaround, we could create dcm files from DcmDatasets so temporarily

**Comment by fedorov** [comment]
I guess. This is not pretty at all. But maybe this is still better, so we can start integrating SEG and SR into Slicer, and not have to wait for PM support.

**Comment by che85** [comment]
I agree. But I have no better idea than that...

**Comment by fedorov** [comment]
@pieper can you give us your thoughts - 

We are developing support for parametric maps in parallel with SEG and SR in dcmqi. Until this PR, SEG/SR did not depend on the non-public functionality in dcmtk, only PM, so we could build PM conditionally, and could start integrating SEG/SR into Slicer without having to wait for PM to be released.

However, we also wanted to provide API that would allow operations on SEG without using file IO, and dcmtk was missing the functionality to support that. What this PR does is add dcmqi API that does not depend on files, but now we depend on non-public dcmtk.

What @che85 proposed is to keep the in-memory API, and, temporarily, save intermediate DICOM files that would then be passed to the public/released dcmtk API. Just to make sure we can proceed with Slicer integration without waiting for PM to be released.

Do you think this is a good idea? I can't think of any other ways to work around...

**Comment by pieper** [comment]
Is there any way to cherry pick the new parts of dcmtk into a branch of
Slicer/dcmtk that could be used to build Slicer for a while?  That is, if
it's just one or two extra methods that provide the needed interface it's
not likely to cause any trouble for the rest of Slicer's use of dcmtk.  If
it's part of a major refactoring of dcmtk then it would be better to wait.

I agree that writing datasets to disk would be better avoided, but it's not
the end of the world and it's probably easier and less likely to cause
problems for anyone else than creating a non-standard fork of dcmtk.

**Comment by michaelonken** [comment]
Maybe I can add the requires API quickly to DCMTK master, what do you exactly need? 

Am 5. August 2016 22:08:05 MESZ, schrieb Andrey Fedorov <notifications@github.com>:
>sorry, I missed that. 
>
>This is frustrating, because this means we cannot integrate this into
>Slicer until the changes in @michaelonken private branch propagate into
>dcmtk master ...
>
>not quite sure how to deal with this
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QIICR/dcmqi/pull/59#issuecomment-237950127

-- 
Sent from mobile, please excuse brief wording

**Comment by fedorov** [comment]
Yes, was thinking about that too, but discarded for some reason. @che85 can you list the commits we need?

Thanks!

**Comment by che85** [comment]
@michaelonken 
- [ ] https://github.com/michaelonken/dcmtk/commit/389dd68db637b373315f6e62160fe5cafacfcfc4
- [ ] https://github.com/michaelonken/dcmtk/commit/68ea21ec8673ee429dca2e454fdc5f8ddf973aa1
- [ ] https://github.com/michaelonken/dcmtk/commit/f618437fab69f50943fa87b615b2c57e4b3b2efe
- [ ] https://github.com/michaelonken/dcmtk/commit/82e831f112fd69eb461da6e282e0754ad48458cf

I think that should be it.

**Comment by michaelonken** [comment]
I'll check that tomorrow morning and let you know

**Comment by michaelonken** [comment]
I merged the related commits into OFFIS DCMTK testing branch, so they go into DCMTK master within the next days.

**Comment by che85** [comment]
Very nice. Thanks Michael.

**Comment by fedorov** [comment]
👍 Thank you!

**Comment by fedorov** [comment]
@che85 let's wait for the dcmtk commits to show up, then update dcmtk package for appveyor and has for other CIs, and then test/merge.

**Comment by che85** [comment]
@michaelonken How much time does it usually take until commits get merged into the DCMTK master branch?

**Comment by michaelonken** [comment]
I'll merge it in today!

**Comment by che85** [comment]
Thanks Michael :)

**Comment by michaelonken** [comment]
The related commits are now in [DCMTK master](http://git.dcmtk.org/?p=dcmtk.git;a=summary). [This commit](http://git.dcmtk.org/?p=dcmtk.git;a=commit;h=728bb7a115db78e9d8c304e8e81498e61eabe0d4) contains the relevant changes. Hope it has everything you need for dcmqi.

**Comment by che85** [comment]
I can move my repository to qiicr if you want

**Comment by fedorov** [comment]
yes, this would be great, it will be easier to have one place where all dcmqi developers can update dcmtk if needed

**Comment by che85** [comment]
I transferred the ownership to qiicr but it seems that I am not allowed to rename it from dcmtk-1 to dcmtk

**Comment by fedorov** [comment]
try now, I made you administrator

**Comment by fedorov** [comment]
I can't rename it either!

**Comment by che85** [comment]
I just did ;)

**Comment by che85** [comment]
Ready to merge ...

**Comment by fedorov** [comment]
great, thanks!

**Pull request merged**
