### PR TITLE
BUG: cmake/SuperBuild: Ensure svn and git paths are propagated

### PR DESCRIPTION
**Pull request by jcfr**
This commit fixes issue #126 by completing the patch initially integrated in
b3ea5fa (BUG: cmake/SuperBuild: Only propagate svn and git paths if valid values)

### CODE REVIEW

**Comment by fedorov** [comment]
Thank you! I confirm this fixed the issue for me!

**Comment by fedorov** [comment]
@jcfr I noticed there are now 2 builds for both appveyor and travis - what are those? Is there a good reason to do 2 builds on a PR?

**Comment by jcfr** [comment]
> Is there a good reason to do 2 builds on a PR?

Not really. This is related to the configuration of appveyor and travis. 

I will commit change like these ones:
* https://github.com/scikit-build/cmake-python-distributions/blob/2d8d16a15351b9b233887224738a056b9687f98a/appveyor.yml#L2-L4
* https://github.com/scikit-build/cmake-python-distributions/blob/2d8d16a15351b9b233887224738a056b9687f98a/.travis.yml#L2-L4

**Comment by jcfr** [comment]
Merging. This changes is not dependent on the platform and there is no need to wait for Travis build to complete.

**Pull request merged**
