### PR TITLE
Roundtrip test and some fixes to inconsistencies between the schema, examples, and JSONMetadataHandler

### PR DESCRIPTION
**Pull request by che85**
Followup on #97.

jsoncompare is from https://github.com/ChannelIQ/jsoncompare, with ChannelIQ/jsoncompare#8 applied.

### CODE REVIEW

**Comment by che85** [comment]
@fedorov Please check if all your commits (except of the last one for adding the missing file) are there.

**Comment by fedorov** [comment]
Did you expect the test would fail too? It sounded from the earlier communication that you expect they should pass, so I wanted to confirm.

**Comment by che85** [comment]
I only wanted to correct the syntax of the test. I didn't mean or check anything else. But I can go ahead and check what's wrong.

**Comment by fedorov** [comment]
ah, ok - makes sense. Can you take a look how much effort would be to fix inconsistencies? I didn't plan to merge until the test passes.

**Comment by che85** [comment]
@fedorov I figured out, that the DICOM-attributes of https://github.com/QIICR/dcmqi/blob/master/data/ct-3slice/liver.dcm
don't even correspond to the attributes defined in https://github.com/QIICR/dcmqi/blob/master/doc/seg-example.json

Instead of using the liver.dcm from the repository, we should use the output from itkimage2segimage otherwise the roundtrip would not make sense because we don't continue working with the produced data, right?

**Comment by fedorov** [comment]
Good observation! It probably makes sense to run itk2seg first using baseline metadata, then run seg2itk on the output of itk2seg, not baseline seg, and use the output metadata file from seg2itk to compare with the baseline json that was used in the itk2seg in the first step. Does this make sense?

**Comment by che85** [comment]
I propose to do the following:
- run itkimage2segimage with liver_seg.nrrd, 01.dcm..., seg-example.json
  - produces liver.dcm
- run segimage2itkimage with product liver.dcm
  - produces nrrd file and meta.json
- comparing meta files by means of comparejson.py with input1 seg-example.json and input2 meta.json

I would set dependencies between the tests in order to have the right order when running them.

**Comment by che85** [comment]
makes sense ;)

**Comment by che85** [comment]
@fedorov ready for merge

**Comment by fedorov** [comment]
Looks great! One question - can you write up a summary of the changes you did to jsoncompare, and consider submitting pull request to the upstream?

**Comment by che85** [comment]
@fedorov I already submitted a PR to the upstream just before I created the PR here. 

https://github.com/ChannelIQ/jsoncompare/pull/9

**Comment by fedorov** [comment]
Very good - I didn't check that repo, so thanks for adding a reference here.

**Comment by che85** [comment]
In my last commit message I added a reference to your PR and my PR of jsoncompare upstream

**Comment by fedorov** [comment]
Sorry, I missed it

**Pull request merged**
