### PR TITLE
Removed key "seriesAttributes" and moved all underlying keys to root level

### LINKED ISSUE #102: Remove seriesAttributes key from schema, example and converter, web interface
@fedorov I think we discussed about that in the past. We wanted to remove the seriesAttributes key and have all sub-keys on the same level like segmentAttributes. 

It would look more like:
https://github.com/QIICR/dcmqi/blob/master/doc/pm-example.json
or
https://github.com/QIICR/dcmqi/blob/master/doc/sr-tid1500-example.json

Webapp priority set to low.

### PR DESCRIPTION
**Pull request by che85**

### CODE REVIEW

**Comment by fedorov** [comment]
let's see if tests clear, but looks ok to me

**Comment by che85** [comment]
Shall I update the webapp as well or is that not priority right now?

**Comment by fedorov** [comment]
if it is non-trivial - not a high priority

**Comment by che85** [comment]
Ok will wait for approving this PR and then might take a look at the webapp because its validation schema is the master...

**Comment by che85** [comment]
@fedorov: passed

**Comment by fedorov** [comment]
👍 looked good to me from the quick look

**Pull request merged**
