### PR TITLE
ci: Update CircleCi config to fix upload of releases

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
xref https://github.com/QIICR/dcmqi/issues/326

**Comment by fedorov** [comment]
Thank you @jcfr!

**Comment by fedorov** [comment]
@jcfr can you push a release tag? I don't have the gpg set up on my computer (had to reinstall the system recently).

**Comment by fedorov** [comment]
@jcfr see below - this is not expected, right? I will remove them manually, and we can keep the release, as long as TravisCI works, I guess...

image

**Pull request merged**
