### PR TITLE
Reorganize library

### PR DESCRIPTION
**Pull request by msmolens**
This builds on #61 by adding a commit to fix the executable link errors on Linux builds.

### CODE REVIEW

**Comment by fedorov** [comment]
@msmolens thanks for the fix - but the windows dashboard is still failing, which started after I added executable only flag. Do you know what is the problem?

**Comment by fedorov** [comment]
Dashboards are green - thanks a lot 👍 @msmolens! Can you tell me how were you able to update the commit without creating a new branch and new PR? The initial commit was failing the tests, but you fixed it with subsequent commits.

**Comment by msmolens** [comment]
@fedorov Great! Here, I updated the commit by amending it and then force pushing the branch to github. This keeps the commit history cleaner once merged. For example, on my branch:

   &lt;edit CMakeLists.txt&gt;
    git add CMakeLists.txt
    git commit --amend
    git push --force

An alternative is to use `git rebase` to squash commits.

But, in general you don't want to force push to a public branch, as it rewrites the history. It is safe in this case where the branch is in my own fork and no one else can write to it.

**Comment by fedorov** [comment]
@msmolens good to know! thanks for the hint, and for the fixes!

**Pull request merged**
