### PR TITLE
Fix ctest/appveyor tests

### PR DESCRIPTION
**Pull request by IlyaFinkelshteyn**

### CODE REVIEW

**Comment by fedorov** [comment]
Thank you for your PR! The problem is it has to be customized better to also work on non-windows platforms. Would you like to do that? If I don't hear back from you, I will fix this myself.

**Comment by IlyaFinkelshteyn** [comment]
Oh yes it was too Windows-centric :) Honestly I am not sure I can switch to this today quickly, can you please fix it yourself?

**Comment by fedorov** [comment]
No worries - I just wanted to give you the right of first refusal! :)

I will fork your fork, and take if from there, so you can keep the ownership of your commit.

Thanks!

**Comment by fedorov** [comment]
superseded by #81

**Pull request closed without merging**
