### PR TITLE
Standalone packaging

### LINKED ISSUE #162: Create packages of dcmqi for all platforms
I thought it is good to have it here so that someone interested in the topic can at least know we thought about this....

### PR DESCRIPTION
**Pull request by jcfr**
This PR will address the packaging of DCMQI as a standalone package:
* DCMQI-0.0.1-Linux.tar.gz
* DCMQI-0.0.1-MacOSX.dmg
* DCMQI-0.0.1-Windows.exe

fixes #162

Here is the content of the Linux package:

```
$ (cd _CPack_Packages/Linux/TGZ/DCMQI-0.0.1-Linux/ && find .)
.
./bin
./bin/itkimage2segimage.xml
./bin/tid1500reader.xml
./bin/segimage2itkimage.xml
./bin/itkimage2segimage
./bin/itkimage2paramap
./bin/tid1500writer
./bin/segimage2itkimage
./bin/tid1500writer.xml
./bin/paramap2itkimage
./bin/itkimage2paramap.xml
./bin/paramap2itkimage.xml
./bin/tid1500reader
./lib
./lib/dcmqi-0.0
./lib/dcmqi-0.0/libITKTransform-4.10.so.1
./lib/dcmqi-0.0/libITKVideoCore-4.10.so
./lib/dcmqi-0.0/libdcmfg.so.3.6.1
./lib/dcmqi-0.0/libdcmnet.so.3.6.1
./lib/dcmqi-0.0/libITKIOSpatialObjects-4.10.so
./lib/dcmqi-0.0/libdcmpmap.so.3.6.1
./lib/dcmqi-0.0/libdcmdsig.so.3.6.1
./lib/dcmqi-0.0/liboflog.so.10
./lib/dcmqi-0.0/libcharls.so.10
./lib/dcmqi-0.0/libITKMetaIO-4.10.so.1
./lib/dcmqi-0.0/libITKIOVTK-4.10.so
./lib/dcmqi-0.0/libITKWatersheds-4.10.so.1
./lib/dcmqi-0.0/libITKIONRRD-4.10.so.1
./lib/dcmqi-0.0/libITKIOTransformMatlab-4.10.so
./lib/dcmqi-0.0/libdcmimage.so
./lib/dcmqi-0.0/libITKBiasCorrection-4.10.so.1
./lib/dcmqi-0.0/libdcmrt.so.10
./lib/dcmqi-0.0/libitkjpeg-4.10.so
./lib/dcmqi-0.0/libITKIOXML-4.10.so.1
./lib/dcmqi-0.0/libdcmtract.so.3.6.1
./lib/dcmqi-0.0/libi2d.so.3.6.1
./lib/dcmqi-0.0/libITKIOPNG-4.10.so
./lib/dcmqi-0.0/libITKKLMRegionGrowing-4.10.so.1
./lib/dcmqi-0.0/libITKgiftiio-4.10.so
./lib/dcmqi-0.0/libITKIOMeta-4.10.so.1
./lib/dcmqi-0.0/libitksys-4.10.so.1
./lib/dcmqi-0.0/libITKOptimizersv4-4.10.so
./lib/dcmqi-0.0/libITKIOSiemens-4.10.so.1
./lib/dcmqi-0.0/libijg8.so.3.6.1
./lib/dcmqi-0.0/libdcmdata.so
./lib/dcmqi-0.0/libITKDICOMParser-4.10.so
./lib/dcmqi-0.0/libdcmsr.so.3.6.1
./lib/dcmqi-0.0/libitkv3p_netlib-4.10.so.1
./lib/dcmqi-0.0/libdcmqrdb.so
./lib/dcmqi-0.0/libijg8.so.10
./lib/dcmqi-0.0/libdcmimgle.so
./lib/dcmqi-0.0/libITKBiasCorrection-4.10.so
./lib/dcmqi-0.0/libdcmpstat.so.3.6.1
./lib/dcmqi-0.0/libITKQuadEdgeMesh-4.10.so
./lib/dcmqi-0.0/libITKniftiio-4.10.so
./lib/dcmqi-0.0/libi2d.so
./lib/dcmqi-0.0/libitkv3p_netlib-4.10.so
./lib/dcmqi-0.0/libdcmiod.so.10
./lib/dcmqi-0.0/libijg16.so
./lib/dcmqi-0.0/libitkvnl_algo-4.10.so
./lib/dcmqi-0.0/libITKOptimizers-4.10.so
./lib/dcmqi-0.0/libdcmfg.so
./lib/dcmqi-0.0/liboflog.so.3.6.1
./lib/dcmqi-0.0/libITKEXPAT-4.10.so
./lib/dcmqi-0.0/libITKIOXML-4.10.so
./lib/dcmqi-0.0/libdcmjpls.so
./lib/dcmqi-0.0/libcmr.so
./lib/dcmqi-0.0/libitkjpeg-4.10.so.1
./lib/dcmqi-0.0/libITKIOStimulate-4.10.so
./lib/dcmqi-0.0/libITKVTK-4.10.so
./lib/dcmqi-0.0/libdcmiod.so.3.6.1
./lib/dcmqi-0.0/libitkimage2segimageLib.a
./lib/dcmqi-0.0/libdcmtls.so.3.6.1
./lib/dcmqi-0.0/libITKIOBioRad-4.10.so.1
./lib/dcmqi-0.0/libITKIONIFTI-4.10.so.1
./lib/dcmqi-0.0/libdcmwlm.so.3.6.1
./lib/dcmqi-0.0/libdcmsr.so.10
./lib/dcmqi-0.0/libitkvcl-4.10.so
./lib/dcmqi-0.0/libdcmtract.so
./lib/dcmqi-0.0/libITKIOIPL-4.10.so.1
./lib/dcmqi-0.0/libdcmdata.so.3.6.1
./lib/dcmqi-0.0/libitkNetlibSlatec-4.10.so.1
./lib/dcmqi-0.0/libitkpng-4.10.so
./lib/dcmqi-0.0/libitkv3p_lsqr-4.10.so
./lib/dcmqi-0.0/libITKPath-4.10.so
./lib/dcmqi-0.0/libofstd.so
./lib/dcmqi-0.0/libITKStatistics-4.10.so.1
./lib/dcmqi-0.0/libdcmtls.so
./lib/dcmqi-0.0/libcharls.so.3.6.1
./lib/dcmqi-0.0/libITKPolynomials-4.10.so.1
./lib/dcmqi-0.0/libdcmseg.so.3.6.1
./lib/dcmqi-0.0/libITKBioCell-4.10.so
./lib/dcmqi-0.0/libdcmseg.so.10
./lib/dcmqi-0.0/libdcmimage.so.10
./lib/dcmqi-0.0/libofstd.so.3.6.1
./lib/dcmqi-0.0/libITKIOCSV-4.10.so.1
./lib/dcmqi-0.0/libitkvnl-4.10.so
./lib/dcmqi-0.0/libITKBioCell-4.10.so.1
./lib/dcmqi-0.0/libdcmnet.so.10
./lib/dcmqi-0.0/libitkvnl-4.10.so.1
./lib/dcmqi-0.0/libITKIOGE-4.10.so.1
./lib/dcmqi-0.0/libijg16.so.10
./lib/dcmqi-0.0/libdcmimgle.so.3.6.1
./lib/dcmqi-0.0/libITKIOImageBase-4.10.so
./lib/dcmqi-0.0/libITKVNLInstantiation-4.10.so.1
./lib/dcmqi-0.0/libITKCommon-4.10.so
./lib/dcmqi-0.0/libITKEXPAT-4.10.so.1
./lib/dcmqi-0.0/libITKIOBMP-4.10.so.1
./lib/dcmqi-0.0/libitkpng-4.10.so.1
./lib/dcmqi-0.0/libitksys-4.10.so
./lib/dcmqi-0.0/libITKIOTIFF-4.10.so
./lib/dcmqi-0.0/libsegimage2itkimageLib.a
./lib/dcmqi-0.0/libdcmjpeg.so
./lib/dcmqi-0.0/libITKIOTransformBase-4.10.so.1
./lib/dcmqi-0.0/libdcmimgle.so.10
./lib/dcmqi-0.0/libdcmjpls.so.3.6.1
./lib/dcmqi-0.0/libITKTransform-4.10.so
./lib/dcmqi-0.0/libdcmfg.so.10
./lib/dcmqi-0.0/libdcmqrdb.so.10
./lib/dcmqi-0.0/libITKIOLSM-4.10.so
./lib/dcmqi-0.0/libdcmrt.so.3.6.1
./lib/dcmqi-0.0/libITKQuadEdgeMesh-4.10.so.1
./lib/dcmqi-0.0/libITKPolynomials-4.10.so
./lib/dcmqi-0.0/libijg12.so.3.6.1
./lib/dcmqi-0.0/libITKWatersheds-4.10.so
./lib/dcmqi-0.0/libdcmdsig.so.10
./lib/dcmqi-0.0/libITKIOPNG-4.10.so.1
./lib/dcmqi-0.0/libITKIOMRC-4.10.so
./lib/dcmqi-0.0/libITKSpatialObjects-4.10.so
./lib/dcmqi-0.0/libITKNrrdIO-4.10.so.1
./lib/dcmqi-0.0/libdcmimage.so.3.6.1
./lib/dcmqi-0.0/liboflog.so
./lib/dcmqi-0.0/libparamap2itkimageLib.a
./lib/dcmqi-0.0/libdcmqrdb.so.3.6.1
./lib/dcmqi-0.0/libdcmseg.so
./lib/dcmqi-0.0/libtid1500readerLib.a
./lib/dcmqi-0.0/libdcmtract.so.10
./lib/dcmqi-0.0/libITKLabelMap-4.10.so.1
./lib/dcmqi-0.0/libcmr.so.10
./lib/dcmqi-0.0/libITKVTK-4.10.so.1
./lib/dcmqi-0.0/libdcmpmap.so
./lib/dcmqi-0.0/libitkimage2paramapLib.a
./lib/dcmqi-0.0/libdcmdsig.so
./lib/dcmqi-0.0/libtid1500writerLib.a
./lib/dcmqi-0.0/libdcmiod.so
./lib/dcmqi-0.0/libITKniftiio-4.10.so.1
./lib/dcmqi-0.0/libITKIOStimulate-4.10.so.1
./lib/dcmqi-0.0/libdcmdata.so.10
./lib/dcmqi-0.0/libITKCommon-4.10.so.1
./lib/dcmqi-0.0/libitkv3p_lsqr-4.10.so.1
./lib/dcmqi-0.0/libitkvnl_algo-4.10.so.1
./lib/dcmqi-0.0/libdcmjpeg.so.10
./lib/dcmqi-0.0/libITKSpatialObjects-4.10.so.1
./lib/dcmqi-0.0/libitkNetlibSlatec-4.10.so
./lib/dcmqi-0.0/libITKOptimizers-4.10.so.1
./lib/dcmqi-0.0/libITKznz-4.10.so
./lib/dcmqi-0.0/libdcmpmap.so.10
./lib/dcmqi-0.0/libITKIOMesh-4.10.so.1
./lib/dcmqi-0.0/libi2d.so.10
./lib/dcmqi-0.0/libofstd.so.10
./lib/dcmqi-0.0/libITKIOIPL-4.10.so
./lib/dcmqi-0.0/libITKKLMRegionGrowing-4.10.so
./lib/dcmqi-0.0/libITKIOBMP-4.10.so
./lib/dcmqi-0.0/libITKIOTransformInsightLegacy-4.10.so.1
./lib/dcmqi-0.0/libITKIOSiemens-4.10.so
./lib/dcmqi-0.0/libITKDICOMParser-4.10.so.1
./lib/dcmqi-0.0/libITKMetaIO-4.10.so
./lib/dcmqi-0.0/libitkvcl-4.10.so.1
./lib/dcmqi-0.0/libijg8.so
./lib/dcmqi-0.0/libITKIOLSM-4.10.so.1
./lib/dcmqi-0.0/libITKVNLInstantiation-4.10.so
./lib/dcmqi-0.0/libITKIOGE-4.10.so
./lib/dcmqi-0.0/libITKVideoIO-4.10.so
./lib/dcmqi-0.0/libcharls.so
./lib/dcmqi-0.0/libITKNrrdIO-4.10.so
./lib/dcmqi-0.0/libdcmtls.so.10
./lib/dcmqi-0.0/libITKgiftiio-4.10.so.1
./lib/dcmqi-0.0/libitktiff-4.10.so.1
./lib/dcmqi-0.0/libdcmnet.so
./lib/dcmqi-0.0/libcmr.so.3.6.1
./lib/dcmqi-0.0/libITKIOJPEG-4.10.so.1
./lib/dcmqi-0.0/libITKStatistics-4.10.so
./lib/dcmqi-0.0/libITKIOTransformMatlab-4.10.so.1
./lib/dcmqi-0.0/libdcmwlm.so.10
./lib/dcmqi-0.0/libITKIOTransformBase-4.10.so
./lib/dcmqi-0.0/libITKIOVTK-4.10.so.1
./lib/dcmqi-0.0/libdcmpstat.so
./lib/dcmqi-0.0/libITKIOImageBase-4.10.so.1
./lib/dcmqi-0.0/libdcmpstat.so.10
./lib/dcmqi-0.0/libITKOptimizersv4-4.10.so.1
./lib/dcmqi-0.0/libITKIOSpatialObjects-4.10.so.1
./lib/dcmqi-0.0/libITKIOGIPL-4.10.so.1
./lib/dcmqi-0.0/libdcmsr.so
./lib/dcmqi-0.0/libITKIONRRD-4.10.so
./lib/dcmqi-0.0/libITKPath-4.10.so.1
./lib/dcmqi-0.0/libITKIOJPEG-4.10.so
./lib/dcmqi-0.0/libdcmjpeg.so.3.6.1
./lib/dcmqi-0.0/libITKMesh-4.10.so.1
./lib/dcmqi-0.0/libITKIONIFTI-4.10.so
./lib/dcmqi-0.0/libITKznz-4.10.so.1
./lib/dcmqi-0.0/libITKMesh-4.10.so
./lib/dcmqi-0.0/libijg12.so
./lib/dcmqi-0.0/libdcmrt.so
./lib/dcmqi-0.0/libijg16.so.3.6.1
./lib/dcmqi-0.0/libITKIOMeta-4.10.so
./lib/dcmqi-0.0/libITKIOCSV-4.10.so
./lib/dcmqi-0.0/libITKVideoCore-4.10.so.1
./lib/dcmqi-0.0/libITKLabelMap-4.10.so
./lib/dcmqi-0.0/libITKIOMesh-4.10.so
./lib/dcmqi-0.0/libITKIOMRC-4.10.so.1
./lib/dcmqi-0.0/libITKIOTIFF-4.10.so.1
./lib/dcmqi-0.0/libdcmwlm.so
./lib/dcmqi-0.0/libijg12.so.10
./lib/dcmqi-0.0/libITKIOGIPL-4.10.so
./lib/dcmqi-0.0/libITKIOBioRad-4.10.so
./lib/dcmqi-0.0/libitktiff-4.10.so
./lib/dcmqi-0.0/libITKIOTransformInsightLegacy-4.10.so
./lib/dcmqi-0.0/libdcmjpls.so.10
./lib/dcmqi-0.0/libITKVideoIO-4.10.so.1
./share
./share/doc
./share/doc/ITK-4.10
./share/doc/ITK-4.10/itksys
./share/doc/ITK-4.10/itksys/Copyright.txt
```

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov

**Comment by fedorov** [comment]
Looks promising JC! Do you want to merge iteratively, or wait until all 3 platforms clear?

**Comment by jcfr** [comment]
Let s wait a little longer

**Comment by fedorov** [comment]
@jcfr do you think the packaging issue will be addressed before the end of Dec 2016?

**Comment by fedorov** [comment]
Issue tracked in #162

**Comment by fedorov** [comment]
content of the generated package on mac:

```
$ find .
.
./.Trashes
find: ./.Trashes: Permission denied
./Applications
./bin
./bin/itkimage2paramap
./bin/itkimage2paramap.xml
./bin/itkimage2segimage
./bin/itkimage2segimage.xml
./bin/paramap2itkimage
./bin/paramap2itkimage.xml
./bin/segimage2itkimage
./bin/segimage2itkimage.xml
./bin/tid1500reader
./bin/tid1500reader.xml
./bin/tid1500writer
./bin/tid1500writer.xml
./lib
./lib/dcmqi-0.0
./lib/dcmqi-0.0/libitkimage2paramapLib.a
./lib/dcmqi-0.0/libitkimage2segimageLib.a
./lib/dcmqi-0.0/libparamap2itkimageLib.a
./lib/dcmqi-0.0/libsegimage2itkimageLib.a
./lib/dcmqi-0.0/libtid1500readerLib.a
./lib/dcmqi-0.0/libtid1500writerLib.a
```

**Comment by jcfr** [comment]
I am experimenting with static build of ITK, DCMTK and SlicerExecutionModel. This will streamline the use and distribution of the standalone executable. For example, it will be possible to use them from any tools that is already built against a different version of ITK.

**Comment by jcfr** [comment]
After enabling static build on the Linux, the content of the package is the following:

```
$ find .
.
./bin
./bin/itkimage2segimage.xml
./bin/tid1500reader.xml
./bin/segimage2itkimage.xml
./bin/itkimage2segimage
./bin/itkimage2paramap
./bin/tid1500writer
./bin/segimage2itkimage
./bin/tid1500writer.xml
./bin/paramap2itkimage
./bin/itkimage2paramap.xml
./bin/paramap2itkimage.xml
./bin/tid1500reader
./share
./share/doc
./share/doc/ITK-4.10
./share/doc/ITK-4.10/itksys
./share/doc/ITK-4.10/itksys/Copyright.txt
```

with the size of each executable being the following:

```
$ ls -1 -sh
total 59M
 11M itkimage2paramap
4.0K itkimage2paramap.xml
 12M itkimage2segimage
4.0K itkimage2segimage.xml
 11M paramap2itkimage
4.0K paramap2itkimage.xml
 12M segimage2itkimage
4.0K segimage2itkimage.xml
6.9M tid1500reader
4.0K tid1500reader.xml
7.2M tid1500writer
4.0K tid1500writer.xml
```

**Comment by fedorov** [comment]
This won't create issues for Slicer extension, right?

**Comment by jcfr** [comment]
> This won't create issues for Slicer extension, right?

Since when the project is built as a Slicer extension, it uses the libraries provided by Slicer, it will not be impacted by this change.

Only executable bundled in the standalone package will be impacted.

That said, it means that the pre-compiled binaries used on windows will have to be rebuilt. Including the suffix `-static` in the archive name would be sensible.

**Comment by jcfr** [comment]
Here is the content of the windows package:

dcmqi-windows-package

**Comment by jcfr** [comment]
And finally here is the content of the MacOSX package:

```
$ tar -xzvf DCMQI-0.0.1-Darwin.tar.gz 
x DCMQI-0.0.1-Darwin/bin/
x DCMQI-0.0.1-Darwin/bin/itkimage2paramap
x DCMQI-0.0.1-Darwin/bin/itkimage2paramap.xml
x DCMQI-0.0.1-Darwin/bin/itkimage2segimage
x DCMQI-0.0.1-Darwin/bin/itkimage2segimage.xml
x DCMQI-0.0.1-Darwin/bin/paramap2itkimage
x DCMQI-0.0.1-Darwin/bin/paramap2itkimage.xml
x DCMQI-0.0.1-Darwin/bin/segimage2itkimage
x DCMQI-0.0.1-Darwin/bin/segimage2itkimage.xml
x DCMQI-0.0.1-Darwin/bin/tid1500reader
x DCMQI-0.0.1-Darwin/bin/tid1500reader.xml
x DCMQI-0.0.1-Darwin/bin/tid1500writer
x DCMQI-0.0.1-Darwin/bin/tid1500writer.xml
x DCMQI-0.0.1-Darwin/share/
x DCMQI-0.0.1-Darwin/share/doc/
x DCMQI-0.0.1-Darwin/share/doc/ITK-4.10/
x DCMQI-0.0.1-Darwin/share/doc/ITK-4.10/itksys/
x DCMQI-0.0.1-Darwin/share/doc/ITK-4.10/itksys/Copyright.txt
```

With the corresponding executable size:

```
$ ls -alsh 
total 208824
    0 drwxr-xr-x  14 kitware  staff   476B Jan 30 23:13 .
    0 drwxr-xr-x   4 kitware  staff   136B Jan 30 23:15 ..
39808 -rwxr-xr-x   1 kitware  staff    19M Jan 30 23:11 itkimage2paramap
    8 -rw-r--r--   1 kitware  staff   2.0K Jan 30 22:14 itkimage2paramap.xml
40832 -rwxr-xr-x   1 kitware  staff    20M Jan 30 23:11 itkimage2segimage
    8 -rw-r--r--   1 kitware  staff   3.3K Jan 30 22:14 itkimage2segimage.xml
39432 -rwxr-xr-x   1 kitware  staff    19M Jan 30 23:11 paramap2itkimage
    8 -rw-r--r--   1 kitware  staff   1.9K Jan 30 22:14 paramap2itkimage.xml
40456 -rwxr-xr-x   1 kitware  staff    20M Jan 30 23:11 segimage2itkimage
    8 -rw-r--r--   1 kitware  staff   2.2K Jan 30 22:14 segimage2itkimage.xml
23600 -rwxr-xr-x   1 kitware  staff    12M Jan 30 23:11 tid1500reader
    8 -rw-r--r--   1 kitware  staff   1.3K Jan 30 22:14 tid1500reader.xml
24648 -rwxr-xr-x   1 kitware  staff    12M Jan 30 23:11 tid1500writer
    8 -rw-r--r--   1 kitware  staff   2.2K Jan 30 22:14 tid1500writer.xml
```

**Comment by fedorov** [comment]
Looks promising, thanks! Let me know when the PR is complete.

**Comment by jcfr** [comment]
Here is a summary of what we have:

* [x] Generate of packages for Linux, MacOSX and Windows:

```
DCMQI-0.0.1-Linux.tar.gz
DCMQI-0.0.1-Darwin.tar.gz
DCMQI-0.0.1-win64.exe
```

* [x] Static build of ITK, DCMTK, SlicerExecutionModel and zlib when doing a standalone package (default build option)

Here are the remaining tasks:

* [ ] 1.a) Update pre-built archives used for appveyor and include the suffic `-static`
* [ ] 1.b) Document the expected layout for the pre-built archive
* [ ] 2) Create script to automatically generate pre-built archive
* [ ] 3) Rename  packages into `dcmqi-linux.tar.gz`, `dcmqi-mac.tar.gz` and `dcmqi-win64.tar.gz`
* [ ] 4) Simplify packages including only executables + README.txt at the root (Currently has folders like `<root>/bin` and `<root>/share` 
* [ ] 5) Update `circle.yml` to use a docker image named `dcmqi-dependencies` that will be used for testing and package generation.
* [ ] 6) Streamline the creation of the `dcmqi` docker image so that it doesn't include development tools.

@fedorov Task **1.a** is mandatory to ensure the CI will remain green on windows and allow package generation directly on appveyor. Could you take care of regenerating them ?

I can then take care of the other *optional* tasks.

**Comment by fedorov** [comment]
> Update pre-built archives used for appveyor and include the suffic -static

JC, do you mean regenerate DCMTK, ITK, SlicerExecutionModel and zlib packages after disabling shared lib build?

**Comment by jcfr** [comment]
> regenerate DCMTK, ITK, SlicerExecutionModel and zlib packages after disabling shared lib build?

Exactly. These could be re-generated based of the the `standalone-packaging` branch available on my fork. It has been rebased against the current master.

**Comment by fedorov** [comment]
It's been a while since I touched those, let's see if I can do it quickly.

> These could be re-generated based of the the standalone-packaging branch available on my fork. 

I am not sure what you mean by this. Those are independent from dcmqi, maybe you mean I should follow how you set the cmake flags.

**Comment by jcfr** [comment]
> Those are independent from dcmqi, maybe you mean I should follow how you set the cmake flags.

Exactly.

**Comment by fedorov** [comment]
I don't know what is going on, but cmake install fails for zlib on appveyor: https://ci.appveyor.com/project/fedorov/zlib. 

I didn't change that part, and it is the same as for dcmtk and itk, so I don't know how to fix it ... I also forgot that I need to build zlib, and then update dcmtk static package to use static zlib, and then same for itk. Maybe we can do initial release without OS-specific packages, and then add it after Feb 1. Those CI issues are sometime tricky for me to figure out.

**Comment by jcfr** [comment]
Thanks for having a look. 

To ensure everything is reproducible, tomorrow, I will plan on updating the build system of dcmqi so that it does the following:
* proceed to installation of ITK, DCMTK and ZLIB as part of the regular build (by default folders like `C:/path/to/dcmqi-build/ITK-install`, `C:/path/to/dcmqi-build/DCMTK-install` and `C:/path/to/dcmqi-build/zlib-install`
* allow customization of the install directory (using option like `-DDCMTK_INSTALL_DIR:PATH=C:\DCMTK-install`)

That way building standalone dcmqi using a command like:
```
cd dmcqi-build
cmake -DDCMTK_INSTALL_DIR:PATH=C:\DCMTK-install -DZLIB_INSTALL_DIR:PATH=C:\zlib-install -DITK_INSTALL_DIR:PATH=C:\ITK-install -G "Visual Studio 12 2013 Win64" ..\dcmqi
cmake --build . --config Release
```
will allow to create the expected directory easily. 

Then archiving them (e.g. with a power shell scripts) will be quite easy.

**Comment by fedorov** [comment]
> That way building standalone dcmqi using a command like:

This is what I tried initially, to package install directory, but it looked to me as if install did not work properly for ITK. I think I reported that issue to you and Matt. I don't recall what was the outcome.

**Comment by jcfr** [comment]
> cmake install fails for zlib on appveyor:

This PR should fix the issue. See https://github.com/fedorov/zlib/pull/1

> didn't change that part, and it is the same as for dcmtk and itk,

Looking closely, DCMTK do **NOT** install cmake using chocolatey. See [here](https://github.com/QIICR/dcmtk/blob/dcmqi/appveyor.yml)

Note that since no version is specified with the `cinst` command, there is not guarantee that build from yesterday will work today. The provided package can change without you knowing ...

**Comment by jcfr** [comment]
Same comment applies for ITK. See https://github.com/fedorov/ITK-dcmqi/blob/stripped-down/appveyor.yml

**Comment by jcfr** [comment]
I confirm that zlib now build as expected. See https://ci.appveyor.com/project/fedorov/zlib

**Comment by fedorov** [comment]
> Same comment applies for ITK.

ITK has cinst: https://github.com/fedorov/ITK-dcmqi/blob/stripped-down/appveyor.yml#L11

I am going to move all those repos under QIICR, and add suffix and description to explain the purpose and differentiate from the official repos.

**Comment by fedorov** [comment]
Also, FYI - the way I set up appveyor, branch-specific versions of the file for dcmqi are ignored. Instead, there is https pointer to the appveyor.yml in master. See discussion http://help.appveyor.com/discussions/problems/5995-restricting-branch-builds-does-not-work. I did this because builds were triggered on branches that are not of interest. If needed, we can clean up branches and revert that setting.

**Comment by jcfr** [comment]
> ITK has cinst

Indeed. And as far as I can tell, as of today, only DCMTK was successfully repackaged and doesn't use `cinst cmake`

i would then suggest to also remove `cinst cmake` from the ITK/appveyor.yml

**Comment by fedorov** [comment]
yes, I am working on reorganizing/updating those. Will update this thread once the static packages are ready or I am stalled.

**Comment by fedorov** [comment]
seems to be ready - see https://github.com/jcfr/dcmqi/pull/1

**Comment by fedorov** [comment]
@jcfr appveyor build/tests pass with static libs https://github.com/QIICR/dcmqi/pull/187

**Comment by jcfr** [comment]
Thanks for the update. I will move forward with this later this afternoon.

**Comment by fedorov** [comment]
@jcfr I thought we worked around the OS-specific packaging with docker, but based on @che85 experiments, he could not get docker (docker, not dcmqi!) to work as expected on Windows 10 Pro. This raises the importance of this PR...

**Comment by fedorov** [comment]
References from @che85 investigation:

https://github.com/docker/docker/issues/27668

> Docker doesn't work on my Windows
i just booted into my native windows
and when trying to start it now, it's saying that virtualization must be enabled
and it is enabled!

**Comment by che85** [comment]
It might be my bootcamp.... and now I completely destroyed my Windows by following this:

http://stackoverflow.com/a/39989990

**Comment by jcfr** [comment]
I am closing this PR. And creating a new directly from dmcqi repo. That way, circle ci will also kick in.

**Pull request closed without merging**
