### PR TITLE
Improve package naming and generate packages

### PR DESCRIPTION
**Pull request by jcfr**
The package has now the following format:

```
dcmqi-vX.Y.Z-(linux|mac|win64)[<version-qualifier>].(tgz|zip)
```

where

* `X.Y.Z` corresponds to the major/minor/patch version define in the `CMakeLists.txt`

* `<version-qualifier>` is set based on rule described below.

This commit adds the target `dcmqiConfigureVersion` that will determine at build time if a *release* or a *development* package is being built. The target is always built.

If a release is being built, the name of the package is:

```
dcmqi-vX.Y.Z-(linux|mac|win64).(tgz|zip)
```

If a development package is being built, the appended <version-qualifier>
will be:

```
-<YYYYMMDD>-<sha_short>
```
where

* `<YYYYMMDD>` is the date of the `HEAD` (last commit of the current Git branch)

* `<sha_short>` the short version of the SHA associated with `HEAD`

For example:

```
dcmqi-1.0.5-linux-20170408-f06b084.tar.gz
```

### CODE REVIEW

**Comment by jcfr** [comment]
@fedorov  Next step will be:
* [ ]  integrate changes enabling automatic upload as GitHub release of the generated packages
* [ ] document the process to make DCMQI release

**Comment by fedorov** [comment]
Very happy to see this development, thank you!

**Comment by jcfr** [comment]
Question: Where should we keep "developer" documentation ? 

Having *User Guide* on Gitbook makes sense (https://qiicr.gitbooks.io/dcmqi-guide/)

I would suggest to have the *Developer Guide* on readthedocs.

I was thinking to setup http://dcmqi.readthedocs.io/  or http://dcmqi-developer-guide.readthedocs.io/ What do you think ?

**Comment by jcfr** [comment]
As a side note, I just enabled the auto-cancel feature on travis:

travis-auto-cancel

**Comment by fedorov** [comment]
> Question: Where should we keep "developer" documentation ?

Let's have this discussion in a dedicated issue #237

**Pull request merged**
