### PR TITLE
BUG: adding nrrd as element instead of having it as default only

### PR DESCRIPTION
**Pull request by che85**
might be related to https://github.com/QIICR/QuantitativeReporting/issues/135

### CODE REVIEW

**Comment by fedorov** [comment]
Add explicit output type flag for paramap tests as well?

**Comment by che85** [comment]
For all of them or for one only to make sure we cover everything?

**Comment by fedorov** [comment]
I just meant for these 2 tests: https://github.com/QIICR/dcmqi/blob/master/apps/paramaps/Testing/CMakeLists.txt#L44-L81. Only for the sake of consistency, since you added it in the seg test.

**Comment by che85** [comment]
Yeah but I only added it for one seg test so that there is one with and one without the flag

**Comment by fedorov** [comment]
ok, that is fine

**Pull request merged**
