### PR TITLE
WIP: allow to specify Procedure Reported code

### PR DESCRIPTION
**Pull request by fedorov**
Before this commit, Procedure Reported was always set to "Imaging procedure".

Related to #30

### CODE REVIEW

**Comment by jcfr** [comment]
This will not work.

I will push a fix later tonight or tomorrow to address this.

We already dealt with that for https://github.com/NeurodataWithoutBorders/pynwb/commit/1c71be682b4ea19aacbcc2f798b8af6cfecbb9fd

**Comment by fedorov** [comment]
> This will not work.

Thanks for monitoring this! I just duplicated the fix proposed by @michaelschwier in https://github.com/millerjv/PkModeling/pull/68.

**Comment by jcfr** [comment]
Great. Do you have a link to their travis log ?  Using `pip2` would be an easier solution then.

**Comment by fedorov** [comment]
Yes, looked like that fix worked for the PR referenced above: https://travis-ci.org/michaelschwier/PkModeling

**Pull request merged**
