### PR TITLE
dcmqi target install step

### PR DESCRIPTION
**Pull request by lorteddie**

### CODE REVIEW

**Comment by lorteddie** [comment]
kind of trying things out here, it works for my setup but i don't ever build superbuild

**Comment by fedorov** [comment]
@rfloca @kislinsk do you mind checking if this will work with MITK superbuild?

**Comment by rfloca** [comment]
Yes sure.

**Comment by fedorov** [comment]
@lorteddie can you let me know if/when this PR is ready for testing? Also, would it make sense to squash some commits, or you think each one deserves to be preserved?

**Comment by lorteddie** [comment]
yes I redid the commits, was definitely too much trial and error commits
I tested that dcmqi target etc is not installed if build via superbuild because cmake will complain that include directories are pointing into the build directory because of ITK and DCMTK. And I tested that it is actually installed if build separately which makes the cmake integration into other projects a lot easier.
If it works for MITK I think we are good here.

**Comment by fedorov** [comment]
Great, thank you! I am going to merge, and see how Slicer dashboard reacts to this. We can revert back if there are issues with Slicer or MITK identified.

**Comment by rfloca** [comment]
Hi, checked it with our current develop branch. It builds and the quick smoke test with our installer also seems to work. If we should still find problems we let you know.

**Pull request merged**
