### PR TITLE
ENH: allow passing of reference DICOMs as directory

### PR DESCRIPTION
**Pull request by fedorov**
Also improved error reporting, made DcmDataset loading more robust

re #182

### CODE REVIEW

**Comment by che85** [comment]
Works fine for me. Just tested locally. 

The only thing that I noticed is that the user can specify both:
  --inputDICOMList 
and 
  --inputDICOMDirectory

**Comment by che85** [comment]
For instance if the user specifies:

```
    --inputDICOMList ${BASELINE}/01.dcm,${BASELINE}/02.dcm,${BASELINE}/03.dcm
    --inputDICOMDirectory ${BASELINE}
```

each dataset will be load twice

**Comment by fedorov** [comment]
Thanks!

> user can specify both

I don't know if it's a good idea or not, but it was intentional

**Comment by che85** [comment]
Yeah it's kind of good if files are spread somehow throughout the file system but on the other hand there should be a check, that the same file won't be loaded twice

**Comment by fedorov** [comment]
I agree, I added to the todo list in #182. I need the docker image, that's why wanted to merge quickly...

**Pull request merged**
