### PR TITLE
Simplify app cmakelists

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov 

Later one we could rename `MODULE_NAME` parameter used in `dcmqi_add_test` to something like `MODULE_CATEGORY`.

**Comment by fedorov** [comment]
is this the work towards fixing #137?

**Comment by jcfr** [comment]
Indeed, adding all tests using one code path is a step toward fixing the failure and avoiding the introduction of new ones.

**Comment by jcfr** [comment]
It will allow (for example) to ensure a launcher is consistently used.

**Comment by fedorov** [comment]
excellent, thanks!

**Pull request merged**
