### PR TITLE
cmake: Enable testing including "CTest" module

### PR DESCRIPTION
**Pull request by jcfr**
Per CMake recommendation, include "CTest" module instead of directly
calling "enable_testing()".

See https://cmake.org/cmake/help/v3.5/module/CTest.html

### CODE REVIEW

**Comment by fedorov** [comment]
Nice! 👍

**Comment by fedorov** [comment]
no point to wait, I am merging this

**Comment by fedorov** [comment]
@jcfr I am sorry - I didn't realize you are still working on it! will you have time to fix the remaining issues related to the discovery of binaries?

**Comment by jcfr** [comment]
I tested locally:

```
$ ctest
Test project /home/jcfr/Projects/dcmqi-Release/dcmqi-build
      Start  1: itkimage2segimage_hello
 1/11 Test  #1: itkimage2segimage_hello ..........   Passed    0.03 sec
      Start  2: itkimage2segimage_makeSEG
 2/11 Test  #2: itkimage2segimage_makeSEG ........   Passed    0.03 sec
      Start  3: segimage2itkimage_hello
 3/11 Test  #3: segimage2itkimage_hello ..........   Passed    0.01 sec
      Start  4: segimage2itkimage_makeNRRD
 4/11 Test  #4: segimage2itkimage_makeNRRD .......   Passed    0.04 sec
      Start  5: seg_meta_roundtrip
 5/11 Test  #5: seg_meta_roundtrip ...............   Passed    0.01 sec
      Start  6: tid1500writer_hello
 6/11 Test  #6: tid1500writer_hello ..............   Passed    0.00 sec
      Start  7: tid1500writer_example
 7/11 Test  #7: tid1500writer_example ............   Passed    0.01 sec
      Start  8: tid1500writer_ct-liver
 8/11 Test  #8: tid1500writer_ct-liver ...........   Passed    0.01 sec
      Start  9: tid1500reader_hello
 9/11 Test  #9: tid1500reader_hello ..............   Passed    0.00 sec
      Start 10: tid1500reader_ct-liver
10/11 Test #10: tid1500reader_ct-liver ...........   Passed    0.01 sec
      Start 11: tid1500_meta_roundtrip
11/11 Test #11: tid1500_meta_roundtrip ...........   Passed    0.01 sec

100% tests passed, 0 tests failed out of 11

Label Time Summary:
segmentation    =   0.12 sec (5 tests)
tid1500         =   0.05 sec (6 tests)

Total Test time (real) =   0.17 sec
```

**Comment by jcfr** [comment]
> didn't realize you are still working on it!

No problem. You merged after I was done :smile: 

> will you have time to fix the remaining issues related to the discovery of binaries

Discovery of tests should now be addressed.

Either or later tonight, I will finalize. Dinner time now.

**Comment by fedorov** [comment]
> Dinner time now.

👍 bon appétit!

**Pull request merged**
