### PR TITLE
Update build system

### PR DESCRIPTION
**Pull request by jcfr**
This PR brings in cleanup and reorganization changes streamlining the overall build system.

The next PR will update the system to allow the extension to be also built as Slicer extension

### CODE REVIEW

**Comment by che85** [comment]
LGTM too, will see if we get any conflicts with the other PR ;)

**Comment by jcfr** [comment]
@che85 I will rebase #110 and address conflict if any.

**Comment by jcfr** [comment]
Thanks for the review.

As a side note, I do not have merge right.

**Comment by fedorov** [comment]
> As a side note, I do not have merge right.

should be fixed now

**Comment by fedorov** [comment]
Cross-linking the issue that this PR is addressing: https://github.com/QIICR/dcmqi/issues/108

**Pull request merged**
