### PR TITLE
BUG: Creating new reader for each input segmentation file (issue #140)

### PR DESCRIPTION
**Pull request by che85**
- otherwise the same segmentation file will be used over and over again

### CODE REVIEW

**Comment by fedorov** [comment]
this definitely makes sense! Does the comment I have in #140 make sense too, or that is not an issue?

**Comment by che85** [comment]
It works the way it is implemented now. No errors and loading into Slicer afterwards shows the right segmentations

**Comment by fedorov** [comment]
Alright! Sorry for the confusion!

**Comment by che85** [comment]
No confusion here. I also only noticed because I debugged it from the beginning. Otherwise I wouldn't have noticed either.

**Comment by jcfr** [comment]
Would it make sense to update the test to prevent regression like this one in the future ?

**Comment by fedorov** [comment]
it definitely would - we discussed this with Christian earlier today

**Comment by fedorov** [comment]
see #142

**Pull request merged**
