### PR TITLE
BUG: fixed typo that has been corrected in most recent dcmtk

### PR DESCRIPTION
**Pull request by che85**
This fix needs to be merged once we are using the most recent dcmtk version mentioned in #233

### CODE REVIEW

**Comment by fedorov** [comment]
and once Slicer is using the most recent dcmtk

**Comment by jcfr** [comment]
Here is the error on Travis:

```

/Users/travis/build/QIICR/dcmqi/libsrc/ParaMapConverter.cpp:136:32: error: no member named 'setRealWorldValueFirstValueMappedSigned' in 'FGRealWorldValueMapping::RWVMItem'; did you mean 'setRealWorldValueFirstValueMappeSigned'?

    realWorldValueMappingItem->setRealWorldValueFirstValueMappedSigned(metaInfo.getFirstValueMapped());

                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                               setRealWorldValueFirstValueMappeSigned

/Users/travis/build/QIICR/dcmqi-build/DCMTK/dcmfg/include/dcmtk/dcmfg/fgrealworldvaluemapping.h:316:23: note: 'setRealWorldValueFirstValueMappeSigned' declared here

  virtual OFCondition setRealWorldValueFirstValueMappeSigned(const Sint16 &value,

                      ^
```

and on appveyor:

```
C:\dcmqi\libsrc\ParaMapConverter.cpp(136): error C2039: 'setRealWorldValueFirstValueMappedSigned' : is not a member of 'FGRealWorldValueMapping::RWVMItem' [C:\dcmqi\dcmqi-build\dcmqi-build\libsrc\dcmqi.vcxproj] [C:\dcmqi\dcmqi-build\DCMQI.vcxproj]
         
             3 Warning(s)
             1 Error(s)
         
```

**Comment by fedorov** [comment]
@jcfr this is expected, as this PR is dependent on upgrading dcmtk to the current master, which has not happened yet.

**Comment by jcfr** [comment]
> this is expected, as this PR is dependent on upgrading dcmtk to the current master, which has not happened yet.

Make sense. Since I looked to make sure it wasn't related to the change I recently contributed .. I also copied the details I found here.

**Comment by fedorov** [comment]
@che85 can you update this PR to use the updated dcmtk version and package for appveyor?

**Comment by fedorov** [comment]
@jcfr CircleCI build is not triggered - do you know if this could be related to your changes?

**Comment by fedorov** [comment]
Ok, so we have 2 problems with this PR, and I have no idea at the moment how to solve those:

1) CircleCI build is not triggered - probably related to the changes done by @jcfr ?

2) all ajv tests are failing with the errors like below - I don't see how these could be caused by the changes in this PR - external schema reference fails to resolve:

```
[00:02:14] 67: schema C:/dcmqi/doc/schemas/segment-context-common-schema.json is invalid
[00:02:14] 67: error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
```

**Comment by fedorov** [comment]
@jcfr it appears that the merges to master do trigger build on CircleCI, but not PRs. Can you think of anything you might have changed to cause this behavior?

**Comment by fedorov** [comment]
Also, the ajv tests that were failing for this PR on appveyor are passing while building master. There is something different about CI configuration for PRs.

**Comment by jcfr** [comment]
> something different about CI configuration for PRs.

Master branch is most likely associated with a build cache that could explain this. I would suggest to clear the build. See https://www.appveyor.com/docs/build-cache/#rest-api

You cold also log to the appveyor worker to investigate. You could add the following at the end of `appveyor.yml`:

```
on_finish:
  - python -m ci_addons --install ../addons
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -block
```

See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#enable-worker-remote-access-ps1

**Pull request merged**
