### PR TITLE
ENH: added dciodvfy test for segmentation (issue #9)

### PR DESCRIPTION
**Pull request by che85**
addresses #9

### CODE REVIEW

**Comment by fedorov** [comment]
very nice - I am excited to see the test results! :)

**Comment by che85** [comment]
Once we have it running on all build systems yeah ....

**Comment by che85** [comment]
@fedorov That's an interesting error. I am wondering why that error doesn't appear when executing dciodvfy on osx 🤔

**Comment by fedorov** [comment]
are you talking about this one?

image

**Comment by fedorov** [comment]
yes, it is interesting that it is inconsistent across the platforms. Let's ask David on the QIICR call on Thu. Maybe the binaries are inconsistent? 

It could help if we had dcmdump for each DICOM object produced by CI.

**Comment by che85** [comment]
@fedorov Ready for merge. Problem was that I installed the dicom3tools wit apt-get and that version is from 2014!

**Comment by fedorov** [comment]
Excellent! This makes sense.

**Pull request merged**
