### PR TITLE
ENH: added pmap/sr dciodvfy and meta roundtrip test and added missing attributes to pmap meta output

### LINKED ISSUE #9: Add proper testing
Specific sub-tasks:

Segmentations
- [x]  add test DICOM data and baselines (@fedorov)
- [x]  seg2itk conversion test: confirm the images are equivalent
- [x]  itk2seg conversion test: 
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

Parametric Maps
- [x]  pmap2itk conversion test: confirm the images are equivalent
- [x]  itk2pmap conversion test: 
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

Structured Report
- [x]  tid1500reader test
- [x]  tid1500writer test
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

### LINKED ISSUE #91: Update paramap2itk converter to initialize DWI parameters
Writing paramap with DWI parameters was added in #85, but not the reverse.

add the following attributes to meta output:
- [x] 'MeasurementMethodCode'
- [x] 'SourceImageDiffusionBValues'
- [x] 'DerivationCode'

### PR DESCRIPTION
**Pull request by che85**
- also set dependencies of dciodvfy tests
- added prefix parameter for output of paramap2itkimage

fixes #9
fixes #91

### CODE REVIEW

**Comment by che85** [comment]
Tests for parametric map roundtrip are expected to fail since there are attributes missing in output metafile

**Comment by fedorov** [comment]
@che85 is there an open issue about missing attributes? If not, can you create one?

**Comment by che85** [comment]
yes I will

**Comment by fedorov** [comment]
@che85 is it issue #91 that describes the missing attributes in the converter output?

**Comment by che85** [comment]
@fedorov Partially yes, but I need to run the tests on my local machine to make sure that there are none missing.

**Comment by che85** [comment]
@fedorov I can confirm:

```
Missing keys: [u'MeasurementMethodCode', u'SourceImageDiffusionBValues']
```

**Comment by che85** [comment]
@fedorov I squashed everything into one commit and tests are passing. Feel free to merge.

**Pull request merged**
