### PR TITLE
Implementation of parametric map itk to dcm converter

### PR DESCRIPTION
**Pull request by che85**
fixes partially #20

works with revision 07e5b0d91b3e0c3dc25419e57343b1ca7c3b8fa1

### CODE REVIEW

**Comment by fedorov** [comment]
when you say "partially" - what is missing?

**Comment by che85** [comment]
from DICOM to itk is missing

**Comment by fedorov** [comment]
ok, thanks - just wanted to check if "to DICOM" is complete

**Comment by fedorov** [comment]
Items not populated properly (probably because they are assigned defaults):

* DERIVED\PRIMARY\VOLUME\MTT - probably the last item should be something else (I think MTT = Mean Transit Time), I think we talked about it, but I need to return to that discussion for details and recall what I suggested
* FrameAnatomy/Laterality
* RescaleSlope is set to 1e-6, but 1 in the output
* LUTLabel should probably be something different from "Just testing"
* did you initialize RealWorldValueLastValueMapped?
* quantity is initialized incorrectly
image
* LUTExplanation should not be "We are mapping trash to junk."
* @michaelonken is this right that RWVM module is replicated in the per-frame sequence? It is identical across frames? Is this a shortcut because you don't have the comparison implemented? If so, does it make sense to give an option to the user to decide what should be shared and what per-frame in FGs?

**Comment by che85** [comment]
I took from "DERIVED\PRIMARY\VOLUME\MTT" https://github.com/michaelonken/dcmtk/blob/paramaps/dcmpmap/tests/make_pmp.cc#L85

I am not sure if more information should go into meta information or how much we can automatically populate
https://github.com/che85/dcmqi/blob/paramaps/lib/ParaMapConverter.cpp#L30-L33

Also see for RealWorldValueLastValueMapped and RescaleSlope 
https://github.com/che85/dcmqi/blob/paramaps/lib/ParaMapConverter.cpp#L191-L195

LUTExplanation should maybe go to meta information?

**Comment by fedorov** [comment]
@michaelonken nevermind that comment addressed to you earlier, this is probably outside of dcmtk. Sorry I didn't have time to look at the source code of the converter in more detail yesterday.

**Comment by fedorov** [comment]
Resulting object displayed in OsiriX:

image

**Comment by che85** [comment]
Nice!

**Comment by che85** [comment]
@fedorov looks good to me. Ready to merge if you want.

**Comment by fedorov** [comment]
Next what I want to do (before passing this for checks and review by @dclunie) is to add an option to import patient/study context from the source series.

**Comment by fedorov** [comment]
CI is doing some serious work helping with debugging platform specific issues, nice! If only we could do something similar with Slicer.

**Comment by che85** [comment]
Yes I agree!

**Comment by fedorov** [comment]
:+1:

**Pull request merged**
