### PR TITLE
Update badge

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@fedorov Let me know what you think.

dcmqi-updated-badges

**Comment by fedorov** [comment]
LGTM! (I've just made a patch release attaching the manually created packages for each of the platforms)

**Comment by jcfr** [comment]
Thanks for the review.

> I've just made a patch release attaching the manually created packages for each of the platforms

I just understood why the docker images wasn't automatically pushed. We need to specified `tags: /[0-9]+\.[0-9]+\.[0-9]+/` so that circleci is triggered each time a numerical tag of the form X.Y.Z is pushed.
See https://circleci.com/docs/configuration/#tags

**Comment by fedorov** [comment]
> We need to specified `tags: /[0-9]+\.[0-9]+\.[0-9]+/`

`git describe --exact-match` is failing for me on the checked out tag, even though it should exact match that commit...

```
~/github/dcmqi on  master! ⌚ 15:56:10
$ git checkout tags/v1.0.1
HEAD is now at 7f40682... Merge pull request #203 from QIICR/standalone-packaging-rebased

~/github/dcmqi on  7f40682! ⌚ 16:02:34
$ git describe --exact-match
fatal: no tag exactly matches '7f40682681608bfcf62199d563e4b70bca15b945'
```

**Comment by fedorov** [comment]
Also, the pattern should be `/v[0-9]+\.[0-9]+\.[0-9]+/`, so should circle.yml look like this (except that describe does not work for me):

```
deployment:
  master: # just a label
    branch: master
    commands:
      - |
        [ "$DOCKER_EMAIL" != "" ] \
        && docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS \
        && docker push qiicr/dcmqi:latest` \
        || echo "skipping docker push"
  release:
    tag: /v[0-9]+(\.[0-9]+)*/
    commands:
      - |
        [ "$DOCKER_EMAIL" != "" ] \
        && docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS \
        && docker push qiicr/dcmqi:`git describe --exact-match 2> /dev/null` \
        || echo "skipping docker push"
```

**Comment by fedorov** [comment]
> git describe --exact-match is failing for me on the checked out tag, even though it should exact match that commit...

Looks this is the answer http://stackoverflow.com/questions/34045598/why-do-git-status-and-git-show-disagree

**Comment by jcfr** [comment]
> git describe --exact-match is failing for me on the checked out tag, even though it should exact match 

I posted some more details here: https://github.com/QIICR/dcmqi/pull/205#issuecomment-281184709

**Pull request merged**
