### PR TITLE
Explore upgrading to use ITKv5

### PR DESCRIPTION
**Pull request by fedorov**
This would be in place of a custom ITKv3, which was done originally to reduce build time of the library due to CI time limits

### CODE REVIEW

**Comment by fedorov** [comment]
No idea why those header files are missing ... asked in https://discourse.itk.org/t/missing-header-files-in-itk-package-i-built/5620

**Comment by fedorov** [comment]
@pieper I am not even sure where to start here - do you have any idea where those errors below are coming from? I built all dependencies (DCMTK, ITK, zlib) using the same VS version, on AppVeyor.

image

image

image

**Comment by jamesobutler** [comment]
> I built all dependencies (DCMTK, ITK, zlib) using the same VS version, on AppVeyor.

@fedorov It looks like you forgot to update the DownloadFile for zlib to download the new VS17 version you made rather than the existing VS12 specified version.

```diff
- $client.DownloadFile("https://github.com/qiicr/zlib-dcmqi/releases/download/zlib-dcmqi-1.2.3-VS12-Win64-Release-static/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
+ $client.DownloadFile(“https://github.com/qiicr/zlib-dcmqi/releases/download/zlib-dcmqi-1.2.3-VS17-Win64-Release-static/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
```

I also see another VS12 reference in:
`$client.DownloadFile("https://github.com/fedorov/SlicerExecutionModel/releases/download/SlicerExecutionModel-dcmqi-VS12-Win64-Release-v0.0.5/SlicerExecutionModel-dcmqi.zip", "C:\SlicerExecutionModel-dcmqi.zip")`

**Comment by fedorov** [comment]
@jamesobutler that was it! Thank you!!! I re-built all the packages, but didn't update zlib and DCMTK!

**Comment by fedorov** [comment]
todo: looks like dockcross is using an older dcmtk version, need to update.

image

**Comment by jamesobutler** [comment]
That looks like the DCMTK version currently used in Slicer. I have an open PR to update to latest DCMTK tag in https://github.com/Slicer/Slicer/pull/6709.

**Pull request merged**
