### PR TITLE
ENH: add a test for generating paramap with values less than 1

### PR DESCRIPTION
**Pull request by fedorov**
Existing example had integer values only

### CODE REVIEW

**Comment by fedorov** [comment]
Context: https://fedorov.gitbooks.io/rsna2016-qirr-dicom4qi/content/instructions/pm.html

**Comment by che85** [comment]
@fedorov Interesting, that the Travis CI build progress is still running ...

**Comment by fedorov** [comment]
It failed due to a timeout. I restarted it earlier today.

The reason I came across this issue is by seeing the warning that converter printed out while running the tests. I don't understand how we didn't see that warning before!

**Comment by fedorov** [comment]
dashboards cleared, so I am merging this

**Pull request merged**
