### PR TITLE
Add headers

### PR DESCRIPTION
**Pull request by fedorov**
replacement for #265 to check if CircleCI will wake up

### CODE REVIEW

**Comment by fedorov** [comment]
@che85  Indeed this woke CircleCI up ...

**Comment by fedorov** [comment]
@che85 can you please remove the last two commits, and force-push to your add_headers branch? I cannot do this anymore, since I am the initiator of the PR.

**Comment by fedorov** [comment]
Actually, let me close this PR. I added you as an explicit collaborator now, and gave you Admin privileges. Let's see if CircleCI build would be triggered now if you make a PR!

**Comment by che85** [comment]
oh just committed

**Pull request closed without merging**
