### PR TITLE
Dcmqi install step improvements

### PR DESCRIPTION
**Pull request by lorteddie**

### CODE REVIEW

**Comment by fedorov** [comment]
@akalali FYI - in case you want to check this in the context of #429

**Comment by fedorov** [comment]
@lorteddie are you still working on this, or it is ready to merge?

**Comment by lorteddie** [comment]
ready from my side, unfortunately i didn't test the last cmake change after removing the build directory, this change fixes paths in the cmake files pointing into the build directory
i also removed the zlib include since i don't understand why it is there (and it fails with dcmtk built with zlib). and since the dcmtk cmake config file still uses library and include paths instead of targets, their dependencies like zlib aren't covered by DCMTK_INCLUDE_DIRS

**Comment by fedorov** [comment]
I will merge, but will see how this plays with the Slicer superbuild.

**Pull request merged**
