### PR TITLE
BUG: MeasurementUnitsCode attribute should be a list

### PR DESCRIPTION
**Pull request by fedorov**
Somehow this error is not detected by ajv. We should report it.

Re #208

### CODE REVIEW

**Comment by che85** [comment]
Let me check our code first....

**Comment by fedorov** [comment]
> Let me check our code first....

Sure .. but just to clarify - what code?

**Comment by che85** [comment]
look at our tests and or schemas

**Comment by fedorov** [comment]
makes sense. I ran validation with and without the lists, and it always validates.

**Pull request merged**
