### PR TITLE
ENH: updated dcmtk revision

### PR DESCRIPTION
**Pull request by che85**
* added includes in CMakeLists.txt for allowing CLion to resolve
references

### CODE REVIEW

**Comment by fedorov** [comment]
@che85 can you make some dummy commit to hopefully wake up CircleCI?

**Comment by jcfr** [comment]
If that helps, Circleci can be triggers using their Api.

Jc

**Comment by che85** [comment]
@fedorov I stopped and restarted it on CircleCI, but still nothing is happening. That's odd!

**Comment by fedorov** [comment]
@che85 this happened before. Perhaps @jcfr knows how to fix this with an API call, but I don't. We can just wait until tomorrow, and make another dummy commit ... This is kludgy, but worked in the past :-(

**Comment by che85** [comment]
@fedorov Do you want to merge this with the dummy commit?

**Comment by fedorov** [comment]
No, I would like to see it pass CircleCI first... once it passes, definitely those need to be squashed first before merging

**Comment by che85** [comment]
@fedorov it passed with the commit before your last one!

**Comment by che85** [comment]
image

**Comment by fedorov** [comment]
Right, but I don't see the build for CircleCI - only Travis and Appveyor

**Comment by che85** [comment]
Oh right now I see what you mean.

**Comment by fedorov** [comment]
I posted a question on the forum: https://discuss.circleci.com/t/build-sometimes-not-triggered-for-a-pull-request/13686

**Comment by fedorov** [comment]
I am going to close this PR and make a new one. Perhaps this has something to do with the permissions of the PR submitter. No idea.

**Pull request closed without merging**
